// https://discord.com/developers/docs/resources/guild#guild-object
import type { Emoji } from "./emoji";
import type { Role } from "./role";
import type { StickerObject } from "./sticker-object";
import type { WelcomeScreenObject } from "./welcome-screen-object";

export type Guild = {
  id: string;
  name: string;
  icon: string | null | undefined;
  icon_hash?: string | null | undefined;
  splash: string | null | undefined;
  discovery_splash: string | null | undefined;
  owner?: boolean;
  owner_id: string;
  permissions?: string;
  region?: string | null | undefined;
  afk_channel_id: string | null | undefined;
  afk_timeout: number;
  widget_enabled?: boolean;
  widget_channel_id?: string | null | undefined;
  verification_level: number;
  default_message_notifications: number;
  explicit_content_filter: number;
  roles: Role[];
  emojis: Emoji[];
  features: string[];
  mfa_level: number;
  application_id: string | null | undefined;
  system_channel_id: string | null | undefined;
  system_channel_flags: number;
  rules_channel_id: string | null | undefined;
  max_presences?: number | null | undefined;
  max_members?: number;
  vanity_url_code: string | null | undefined;
  description: string | null | undefined;
  banner: string | null | undefined;
  premium_tier: number;
  premium_subscription_count?: number;
  preferred_locale: string;
  public_updates_channel_id: string | null | undefined;
  max_video_channel_users?: number;
  max_stage_video_channel_users?: number;
  approximate_member_count?: number;
  approximate_presence_count?: number;
  welcome_screen?: WelcomeScreenObject;
  nsfw_level: number;
  stickers?: StickerObject[];
  premium_progress_bar_enabled: boolean;
  safety_alerts_channel_id: string | null | undefined;
};
